sonar.projectKey=rbarrimond_health_assistant
sonar.projectName=health-assistant
sonar.sources=TrainingAnalyticsPlatform,function_app.py,utils.py,config
sonar.tests=tests
sonar.python.version=3.13
sonar.exclusions=\
  .venv/**,\
  .pyenv/**,\
  build/**,\
  dist/**,\
  *.egg-info/**,\
  scripts/**,\
  **/__pycache__/**
